color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.18823034060187638
  lightness: 0.7810964852105826
  saturation: 0.9630095886532217
  rhythmicContrast: 0.05866568814963102
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: massive surprise
layout_spectrum: 0.9277679971419275
typography_spectrum: 0.8201415287330747
content: []
title: Sales and Marketing for the enabled
description: Inbound micro universe 2.0
purpose:
  - type: contact
    url: 'mailto:ah@contentpepper.de'
    label: Contact me
author:
  name: Alexander Hummelt
  email: ah@contentpepper.de
analytics:
  twitter: ''
github: true
